// export { default as component } from './Folder/File'
export { default as Navbar } from './Home/Navbar/Navbar.jsx'
export { default as Header } from './Home/Header/Header.jsx'
export { default as Brand } from './Home/Brand/Brand.jsx'
export { default as Feature } from './Home/Feature/Feature.jsx'
export { default as WhatSignTalk } from './Home/WhatSignTalk/WhatSignTalk.jsx'
export { default as Footer } from './Home/Footer/Footer.jsx'
export { default as LSFHeader } from './Learn/LsfHeader/LsfHeader.jsx'
export { default as AlphabetContainer } from './Alphabet/AlphabetContainer/AlphabetContainer.jsx'