version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@3.2.3
jobs:
  test: 
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_test: # this can be any name you choose
    jobs:
      - test
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload
